<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('Forms.CheckboxForm.Title')?></h1>
<p><?php TransOut('Forms.CheckboxForm.Description') ?></p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('Forms.CheckboxForm.Legend') ?></legend>
        <div class="row">
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('Name') ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('Label') ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('CheckedValue') ?>
            </div>
        </div>
         <div class="row">
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('Template') ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('CssID') ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('CssClass') ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('Required') ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('Checked') ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('DisableFrontendValidation') ?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderAccessElements(); ?>
    <?php echo $this->RenderSubmit(); ?>
</form>