<?php if ($this->label): ?>
<label class="inline" for="<?php HtmlOut($this->id) ?>">
<?php endif; ?>
    <input name="<?php HtmlOut($this->name) ?>" id="<?php HtmlOut($this->id)?>" type="checkbox" value="<?php HtmlOut($this->checkedValue)?>"<?php if ($this->required): ?> required="required"<?php endif; ?><?php if ($this->classes): ?> class="<?php HtmlOut($this->classes)?>"<?php endif ?><?php if ($this->checked): ?> checked="checked"<?php endif; ?> />
<?php if ($this->label): ?>
    <?php HtmlOut($this->label); ?>
</label>
<?php endif; ?>
<?php if ($this->checkFailed): ?>
<small class="error">
    <?php foreach ($this->errors as $error): ?>
    <span>
        <?php HtmlOut($error); ?>
    </span>
    <?php endforeach ?>
</small>
<?php endif; ?>